TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Controllers/DashboardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Web.Script.Serialization;
using System.Data.SqlClient;
using System.Configuration;
using TadaTruckMonitoring.Models;
using System.Text;
using TadaTruckMonitoring.Entity;
using TadaTruckMonitoring.Control;

namespace TadaTruckMonitoring.Controllers
{
    [SessionTimeout]
    public class DashboardsController : Controller
    {
        User_Entity _userentity = new User_Entity();
        User_Model _usermodel = new User_Model();
        public ActionResult Home()
        {

                    //Session["FULL_NAME"] = "";
                    //Session["USER_NAME"] = "";
                    //Session["LANG"] = "";
                    //Session["SGID"] = "";
                    //Session["C_PARM"] = "";
                    //Session["SITE"] = "";
                    //Session["FORM"] = "";
                    //Session["APP"] = "";
                    //Session["GROUP"] = "";
                    //Session["CURR_LANG"] =  "";
                    //Session["GLOBAL_CONN"] = "";

            if (Session["LOGIN_STAT"] != "SUCCESS")
            {
                Session["GLOBAL_CONN"] = ConfigurationManager.ConnectionStrings["INITConnection"].ConnectionString;
                // Globals.SetGlobalConnection(ConfigurationManager.ConnectionStrings["INITConnection"].ConnectionString);
                return this.RedirectToAction("Login", "Login");
                //   return;
            }
            return View();

            //DataSet dsMFG = new DataSet();
            //dsMFG = _usermodel.getLoadMainMenus(Session["LANG"].ToString(), Session["APP"].ToString(), Session["GROUP"].ToString(), "", Session["USER_NAME"].ToString());
            //return View(dsMFG);
            //ViewBag.Count = new List<string>()
            //{
            //    "1",
            //    "2"
            //};

          //  return View();
        }

        public ActionResult Menu_home()
        {
            StringBuilder sb = new StringBuilder();

            sb.Append("<li class=\"\">");
            sb.Append(Environment.NewLine);
            sb.Append("<a href=\"\">");
            sb.Append("Internal Movements of ID Sheets");
            sb.Append("</a>");
            sb.Append(Environment.NewLine);
            sb.Append("</li>");
            return View(sb.ToString());
        }
  

        public ActionResult MVTS()
        {
            return View();
        }

        public ActionResult Dashboard_2()
        {
            return View();
        }

        public ActionResult Dashboard_3()
        {
            return View();
        }

        public ActionResult Dashboard_4()
        {
            return View();
        }

        public ActionResult Dashboard_4_1()
        {
            return View();
        }

        public ActionResult Dashboard_5()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GET_FICH_DETAILS(string flag, string fich_no, string bay_rack, string lang, string userid, string c_racklevel, string da_no)
        {

            string JsonData = string.Empty;
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
            SqlCommand cm = new SqlCommand("SP_LITE_WEB_MVTS", con);
            cm.CommandType = CommandType.StoredProcedure;

            cm.Parameters.AddWithValue("@FLAG", flag);
            cm.Parameters.AddWithValue("@FICH", fich_no);
            cm.Parameters.AddWithValue("@BAYRACK", bay_rack);
            cm.Parameters.AddWithValue("@LANG", lang);
            cm.Parameters.AddWithValue("@USERID", userid);
            cm.Parameters.AddWithValue("@C_RACKLEVEL", c_racklevel);
            cm.Parameters.AddWithValue("@DA_NO", da_no);

            SqlDataAdapter da = new SqlDataAdapter(cm);

            DataSet ds = new DataSet();
            da.Fill(ds);
            string jsonTBL1 = getjsondata(ds.Tables[0]);
            var _LstHolding = new { jsonTBL1 };
            return Json(_LstHolding, JsonRequestBehavior.AllowGet); 
        }

        [HttpGet]
        public JsonResult SAVE_FICH_DETAILS(string flag, string fich_no, string bay_rack, string lang, string userid, int c_racklevel, string da_no, string txmode, string t_device, string halfframe, string idoc_req)
        {
            string JsonData = string.Empty;
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
            SqlCommand cm = new SqlCommand("SP_LITE_WEB_MVTS_SAVE", con);
            cm.CommandType = CommandType.StoredProcedure;
            cm.Parameters.AddWithValue("@FLAG", flag);
            cm.Parameters.AddWithValue("@FICHE", fich_no);
            cm.Parameters.AddWithValue("@BAYRACK", bay_rack);
            cm.Parameters.AddWithValue("@LANG", lang);
            cm.Parameters.AddWithValue("@USERID", userid);
            cm.Parameters.AddWithValue("@C_RACKLEVEL", c_racklevel);
            cm.Parameters.AddWithValue("@DA", da_no);
            cm.Parameters.AddWithValue("@TXMODE", txmode);
            cm.Parameters.AddWithValue("@T_DEVICE", t_device);
            cm.Parameters.AddWithValue("@HALFFRAME", halfframe);
            cm.Parameters.AddWithValue("@IDOC_XREQ", idoc_req);
            SqlDataAdapter da = new SqlDataAdapter(cm);
            DataSet ds = new DataSet();
            da.Fill(ds);
            string jsonTBL2 = getjsondata(ds.Tables[0]);

            
            //JsonData = getjsondata(dt);

            var _LstHolding2 = new { jsonTBL2 };
            return Json(_LstHolding2, JsonRequestBehavior.AllowGet); 
        }

        
        public string FICH_STATUS_DETAILS(string strRequestNO)
        {
          //  string returnedval = "json retured";
          //  string returnedval2 = "json retured";

            string JsonData = string.Empty;


            Console.WriteLine(strRequestNO.ToString());
            DataTable dt = new DataTable();
            dt.Columns.Add("Status");
            dt.Columns.Add("value");

            DataRow _val = dt.NewRow();
            _val["Status"] = "success";
            _val["value"] = "1";
            dt.Rows.Add(_val);


            JsonData = getjsondata(dt);
            return JsonData;
                              
        }

        public string getjsondata(DataTable dt)
        {
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> Rows = new List<Dictionary<string, object>>();
            Dictionary<string, object> Row = null;
            foreach (DataRow dr in dt.Rows)
            {
                Row = new Dictionary<string, object>();
                foreach (DataColumn col in dt.Columns)
                {
                    Row.Add(col.ColumnName.Trim(), dr[col]);
                }
                Rows.Add(Row);
            }
            return jsSerializer.Serialize(Rows);
        }

        public string FORMSEARCH(string text)
        {
            try
            {
                SqlConnection con = null;

                if (Session["GLOBAL_CONN"] == " " || Session["GLOBAL_CONN"] == null)
                {
                    con = new SqlConnection(ConfigurationManager.ConnectionStrings["INITConnection"].ConnectionString);

                }
                else
                {
                    con = new SqlConnection(Session["GLOBAL_CONN"].ToString());
                }
                string result = string.Empty;
                string lang = Session["LANG"].ToString();
                string user = Session["SGID"].ToString();
                SqlCommand cmd = new SqlCommand("select count(*) from xt_xcon where C_CON='" + text + "'", con);
                con.Open();
                int count = Convert.ToInt16(cmd.ExecuteScalar());
                con.Close();
                if (count == 1)
                {
                    SqlCommand cm = new SqlCommand("SP_LITE_LOAD_MENUSUBMENUNEW", con);
                    cm.CommandType = CommandType.StoredProcedure;
                    cm.Parameters.AddWithValue("@LANGUAGE", lang);
                    cm.Parameters.AddWithValue("@APPLICATION", "LG");
                    cm.Parameters.AddWithValue("@USERGROUP", Session["GROUP"].ToString());
                    cm.Parameters.AddWithValue("@MENUGROUP", "");
                    cm.Parameters.AddWithValue("@USERID", user);

                    SqlDataAdapter da = new SqlDataAdapter(cm);
                    DataSet dt = new DataSet();
                    da.Fill(dt);
                    if (dt.Tables[1].Rows.Count > 0)
                    {
                        for (int i = 0; i < dt.Tables[1].Rows.Count; i++)
                        {
                            DataRow dr = dt.Tables[1].Rows[i];
                            if (dr["C_CON"].ToString() == text)
                            {
                                return (dr["LT_ACTION"].ToString() + "," + dr["LT_CONTROL"].ToString());
                            }
                        }
                    }
                    return ("InternalServerError" + "," + "Pages");
                }
                else
                {
                    return ",";
                }
            }
            catch
            {
                return ",";
            }
        }

        public string Menu()
        {
            SqlConnection con = null;
            if (Session["GLOBAL_CONN"] == " " || Session["GLOBAL_CONN"] == null)
            {
                con = new SqlConnection(ConfigurationManager.ConnectionStrings["INITConnection"].ConnectionString);
            }
            else
            {
                con = new SqlConnection(Session["GLOBAL_CONN"].ToString());
            }
            string result = string.Empty;
            string lang = Session["LANG"].ToString();

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace TadaTruckMonitoring.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/
        public ActionResult Menu()
        {
            StringBuilder sb = new StringBuilder();

            sb.Append("<li class=\"\">");
            sb.Append(Environment.NewLine);
            sb.Append("<a href=\"\">");
            sb.Append("Internal Movements of ID Sheets");
            sb.Append("</a>");
            sb.Append(Environment.NewLine);
            sb.Append("</li>");

            //string return_data = "<li class=""><a href="">Internal Movements of ID Sheets</a></li>";
            return View(sb.ToString());
            //return View();
        }
	}
}

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        
    </div>
    <div>
        <strong></strong> &copy; Copyright 2019 Saint Gobain. All Rights Reserved.
    </div>
</div>

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_Layout.cshtml
@using System.Data
@model System.Data.DataSet
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Orion Truck Monitoring</title>

    <link rel="icon" href="~/Images/orion_images/Orion.ico" type="image/x-icon" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
    @*<link href="~/Content/responsive_dataTables.css" rel="stylesheet" />*@
    @*<link href="~/Content/datatable_css.css" rel="stylesheet" />*@
    @*<link href="~/Content/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
    <script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>*@
    <!-- Primary Inspinia style -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")

</head>
<body style="font-size:12px" class="canvas-menu">

    <!-- Skin configuration box -->
    <!-- @Html.Partial("_SkinConfig") -->
    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @*@Html.Partial("_Navigation_Changed", Model)*@

        <!-- Page wraper -->
        @*<div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">*@
        <div id="page-wrapper" class="gray-bg">

            <!-- Top Navbar -->
            @*@Html.Partial("_TopNavbar")*@

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->
        <!-- Right Sidebar -->
        @*@Html.Partial("_RightSidebar")*@

    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")


    <script src="~/Scripts/plugins/jquery-ui/jquery-ui.min.js"></script>
    @*<script src="~/Scripts/plugins/metisMenu/metisMenu.min.js"></script>*@
    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ajaxStart(function () {
            $('#ajaxBusy').show();
        });
        $(document).ajaxStop(function () {
            $('#ajaxBusy').hide();
        });
        $(function () {
            $(document).ajaxComplete(function (a, xhr, c) {
                if (xhr.status == 403 && xhr.responseText.indexOf("LogOut") != -1) {
                    swal({
                        title: 'Session Expires Login to Continue..!',
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "OK",
                        closeOnConfirm: true,
                        animation: true
                    }, function () {
                        window.location.href = "@Url.Action("Login", "Login")";
                    })
                }
            });
        });

        $(window).resize(function () {
            $('#page-wrapper').css('min-height', $(window).height());
        });


        $(document).ready(function () {
            $('#page-wrapper').css('min-height', $(window).height());
            $('body').append('<div id="ajaxBusy" class="loading" style="display:none"><img src="../Images/orion_images/loading.gif" alt="Loading..." /></div>');
        });
    </script>
    <style type="text/css">
        .loading {
            position: fixed;
            z-index: 9999999999;
            height: 2em;
            width: 2em;
            overflow: show;
            margin: auto;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }

            /* Transparent Overlay */
            .loading:before {
                content: '';
                display: block;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0,0,0,0.3);
            }
    </style>  
</body>
</html>

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_Layout_2.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INSPINIA | @ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
     
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->     
    @Styles.Render("~/font-awesome/css")                                                
    @Styles.Render("~/Content/css")
</head>
<body class="top-navigation">

    <!-- Skin configuration box -->
    @Html.Partial("_SkinConfig")

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar2")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_Layout_3.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INSPINIA | @ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
     
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->     
    @Styles.Render("~/font-awesome/css")                                                
    @Styles.Render("~/Content/css")
</head>
<body class="fixed-sidebar no-skin-config full-height-layout">

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_Layout_4.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INSPINIA | @ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
     
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->     
    @Styles.Render("~/font-awesome/css")                                                
    @Styles.Render("~/Content/css")
</head>
<body class="canvas-menu">

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_NavigationOffCanvas")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

    <script>
        $('body.canvas-menu .sidebar-collapse').slimScroll({
            height: '100%',
            railOpacity: 0.9
        });
    </script>

</body>
</html>

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_Navigation_Changed.cshtml
@using System.Data
<style>
    .navbar-static {
        left: 300px; /* just an estimate of your sidebar's width */
        width: calc(100% - 200px);
    }
</style>
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header" style="padding:0">
                <div class="dropdown profile-element" style="text-align:center">
                    <span>
                        <img src="~/Images/orion_images/logo_master1.png" alt="image" style=" margin:auto; padding: 15px 0" />
                    </span>
                </div>
                <div class="logo-element">
                    <img src="~/Images/orion_images/Orion.ico" />
                </div>
            </li>
            <li><a href="@Url.Action("UserStatus", "UserStatus")"><i class="fa fa-bar-chart"></i><span class="nav-label" data-i18n="nav.menulevels">Home </span></a></li>
            <li><a href="@Url.Action("TransactionUser", "TranasctionUser")"><i class="fa fa-th-large"></i><span class="nav-label" data-i18n="nav.menulevels">Master </span></a></li>
            <li><a href="@Url.Action("TransactionUserDetails", "TransactionUserDetails")"><i class="fa fa-user"></i><span class="nav-label" data-i18n="nav.menulevels">Transaction User Details </span></a></li>
            <li><a href="@Url.Action("SOD", "SOD")"><i class="fa fa-address-book"></i><span class="nav-label" data-i18n="nav.menulevels">SOD </span></a></li>
            <li><a href="@Url.Action("CriticalTransaction", "CriticalTransaction")"><i class="fa fa-key"></i><span class="nav-label" data-i18n="nav.menulevels">Critical Transaction </span></a></li>
            <li><a href="@Url.Action("UserProfileAssignment", "UserProfileAssignment")"><i class="fa fa-paste"></i><span class="nav-label" data-i18n="nav.menulevels">User Profile Assignment </span></a></li>
            <li><a href="@Url.Action("UserRequest", "UserRequest")"><i class="fa fa-envelope"></i><span class="nav-label" data-i18n="nav.menulevels">User Request </span></a></li>
            <li><a href="@Url.Action("CheckStatus", "CheckStatus")"><i class="fa fa-reply"></i><span class="nav-label" data-i18n="nav.menulevels">Check Status</span></a></li>
            <li><a href="@Url.Action("LOG_OUT_BTN", "Login")"><i class="fa fa-sign-out"></i><span class="nav-label" data-i18n="nav.menulevels">Logout </span></a></li>
        </ul>
    </div>
</nav>

TadaTruckMonitoringDevelopment/TadaTruckMonitoring/Views/Shared/_TopNavbar.cshtml
@using System.Data
@model System.Data.DataSet

<div class="row border-bottom">
    <nav class="navbar navbar-static-top" style="margin:0; min-height:20px !important" role="navigation">
        <div class="navbar-header" style="margin: 0; padding:0">
            @*<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#" style="margin: 5px;"><i class="fa fa-bars"></i> </a>*@
            @*<form role="search" class="navbar-form-custom" method="post" action="" style="margin: 0; padding:0">


                    <input type="text" placeholder="Enter Transaction Code..." data-provide="typeahead" style="height:42px"
                           data-source="@Html.Gettranscationcode()" maxlength="5" class="form-control" id="top-search" onkeydown="key()">


                </form>*@
        </div>
        <div class="navbar-header" style="margin: 0; padding:0; display:none">
            <form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">

                    <a href="#" onclick="keydown()" style="font-size: 20px; color: #1ab394">
                        <i class="fa fa-search"></i>
                    </a>

                </div>
            </form>
        </div>

        <ul class="nav navbar-top-links navbar-right">
            <li>
                @*<span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">Welcome </span>*@

                <span class="m-r-sm" data-i18n="topnav.welcometext"><i class="fa fa-user-circle-o"></i> @Html.GETUSERNAME()</span>
            </li>

            <li>
                <a href="@Url.Action("LOG_OUT_BTN", "Login")">
                    <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext"> <i class="fa fa-sign-out"></i> Log out</span>
                </a>
            </li>
            @*<li>
                    <a class="right-sidebar-toggle">
                        <i class="fa fa-tasks"></i>
                    </a>
                </li>*@
        </ul>
    </nav>
</div>

<link href="~/Content/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>
<script type="text/javascript">
    @*$(document).ready(function () {
        $.ajax({
            contentType: 'application/json; charset=utf-8', type: 'GET',
            url: '@Url.Action("Gettranscationcode", "Dashboards")',
            data: {}, // for get side decrypt DB conn string to assign Globals.conn
            async: false, cache: false,
            success: function (result) {
                alert(result);
                $('#top-search').typeahead({
                    source: result
                });
            }
        });
    })*@
    function keydown1() {
        var form = $('#top-search').val().toUpperCase();
        if (form != '') {
            $.ajax({
                contentType: 'application/json; charset=utf-8', type: 'GET',
                url: '@Url.Action("FORMSEARCH", "Dashboards")',
                data: { text: form }, // for get side decrypt DB conn string to assign Globals.conn
                async: false, cache: false,
                success: function (result) {
                    if (result == ',') {
                        //  toastr.warning("sd");
                        swal({
                            title: "Invalid Transaction Code...",
                            type: "warning"
                        });
                    }
                    else {
                        var res = result.split(",");
                        window.location.href = '../' + res[1] + '/' + res[0];
                    }
                    //window.location.href = "@Url.Action("Breakage", "BreakageIndex")"

                }
            });
        }
        else {
            swal({
                title: "Enter Transaction Code..",
                text: "",
                type: "warning"
            });
        }
    }
    function key() {
        if (event.keyCode == 13) {
            keydown1();
            event.preventDefault();
            return false;
        }
    }
</script>